export const CONFIG = {
  maxPlayers: 10,
  islandRadius: 92,
  cell: 4,
  story: 3,
  gravity: 24,
  jump: 8.2,
  speed: 7.2,
  sprint: 10.4,
  airSpeed: 5.4,
  eye: 1.52,
  radius: 0.38,
  startWood: 90,
  startHp: 100,
  dropHeight: 58,
  buildCost: 10,
  treeWood: 38,
  netHz: 12,
  names: [
    "INK",
    "NIB",
    "TICK",
    "DASH",
    "HASH",
    "DOT",
    "SLANT",
    "GLYPH",
    "SKETCH",
    "SCRIB",
    "MARK",
    "STROKE",
  ],
  botNames: [
    "BOT-NIB",
    "BOT-DOT",
    "BOT-HASH",
    "BOT-SLANT",
    "BOT-GLYPH",
    "BOT-MARK",
    "BOT-TICK",
    "BOT-DASH",
    "BOT-STROKE",
  ],
  faces: ["smile", "cool", "wink", "shock", "frown", "blank"],
  hats: ["none", "tophat", "cap", "beanie", "antenna"],
  packs: ["none", "pack", "satchel", "bedroll"],
  colors: ["#14120f", "#d0122a", "#2f5d50", "#3b4cc5", "#c45c12", "#6b3fa0", "#1c6ea4", "#af9b3c"],
  fov: 78,
  adsSpread: 0.28,
  weapons: {
    pistol: { name: "Stick Pistol", dmg: 18, rpm: 170, spread: 0.018, mag: 12, reserve: 36, speed: 420, pellets: 1, adsFov: 52 },
    rifle: { name: "Stick Rifle", dmg: 20, rpm: 420, spread: 0.012, mag: 24, reserve: 72, speed: 620, pellets: 1, adsFov: 48 },
    shotgun: { name: "Stick Boomstick", dmg: 11, rpm: 62, spread: 0.075, mag: 5, reserve: 20, speed: 280, pellets: 6, adsFov: 58 },
    sniper: { name: "Stick Longshot", dmg: 68, rpm: 42, spread: 0.002, mag: 4, reserve: 12, speed: 820, pellets: 1, adsFov: 32 },
  },
  storm: [
    { wait: 18, shrink: 22, radius: 78, dps: 1.2 },
    { wait: 14, shrink: 18, radius: 48, dps: 2.4 },
    { wait: 12, shrink: 16, radius: 28, dps: 4.5 },
    { wait: 10, shrink: 14, radius: 14, dps: 8 },
    { wait: 8, shrink: 12, radius: 6, dps: 12 },
  ],
};

export const DEFAULT_PROFILE = {
  name: "STICK-01",
  face: "smile",
  hat: "tophat",
  pack: "pack",
  color: "#d0122a",
};
